author: "Patrick Houtman - PH-F"
category: "http"
summary: "HTTP POST user's messages to target URL when user is offline for eJabberd 17.01"
home: "https://github.com/PH-F/mod_offline_http_post_group"
url: "https://github.com/PH-F/mod_offline_http_post_group"